### ISSUE TITLE
您好，歪个楼。我想问一下作者intro中的shirt符号、hat符号是怎么插入文中的？我用emoji这个包没找到这几个符号，可以解答一下吗？

### ISSUE THREAD

**Issue by xlwu2270** [CRIPAC-DIG/LATTICE#2]

**Comment by JinghaoZ** [comment]
需要先搜集图片素材，然后以图片形式插入的。具体可以参考 https://tex.stackexchange.com/questions/139143/how-to-set-an-inline-figure-matching-the-text-height

**Comment by xlwu2270** [comment]
哇，太谢谢了！感谢感谢！
