### ISSUE TITLE
显卡问题

### ISSUE THREAD

**Issue by epiphany1111** [CRIPAC-DIG/LATTICE#3]
您好，非常感谢能够看到这样优秀的工作，有一点想要请教，我把项目代码放在3090显存为24G的单卡上运行，出现cuda out of memory的错误，故想向作者询问一下在训练时使用的显卡，以及代码需要多大的显存才能运行。

**Comment by JinghaoZ** [comment]
你好，感谢你对我们工作的关注！
我们使用的是32G的V100训练；此外，我们在扩展文章的代码 https://github.com/CRIPAC-DIG/MICRO 中增加了稀疏化构图操作，可以在24G的单卡上运行。

**Comment by epiphany1111** [comment]
非常感谢您的解答
